<?php

$finder = (new PhpCsFixer\Finder())
    ->in(__DIR__)
    ->exclude('var')
    ->notPath([
        'config/bundles.php',
        // Generated by the Symfony Flex recipe on `composer install`, not hand-written.
        // Its docblocks contain `@type`, which the @Symfony rule set rewrites to
        // `@var` — corrupting the reference and failing the fixer on a clean checkout.
        'config/reference.php',
    ])
;

return (new PhpCsFixer\Config())
    ->setRules([
        '@Symfony' => true,
    ])
    ->setFinder($finder)
;
